name: build-deploy-step
on:
  workflow_call:
    inputs:
      variant:
        description: 'Variant to build'
        default: ''
        required: true
        type: string
jobs:
  build-and-release:
    runs-on: self-hosted
    steps:
    - name: Deploy
      run: |
        echo "Hello world"
      shell: bash
