name: build-deploy-step
on:
  workflow_call:
    inputs:
      variant:
        description: 'Variant to build'
        default: ''
        required: true
        type: string
      branch_tags:
        type: boolean
        description: 'Include branch tags'
        default: false
        required: false
jobs:
  build-and-release:
    runs-on: self-hosted
    steps:
    - name: Deploy
      run: |
        echo "Hello world"
        echo ${{ inputs.variant }}
      shell: bash
